#ifndef TSETLIN_MACHINE_VERIFIER_H
#define TSETLIN_MACHINE_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef TSETLIN_MACHINE_READER_H
#include "tsetlin_machine_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int TsetlinMachine_Parameters_verify_table(flatcc_table_verifier_descriptor_t *td);
static int TsetlinMachine_ClauseWeightsTensor_verify_table(flatcc_table_verifier_descriptor_t *td);
static int TsetlinMachine_AutomatonStatesTensor_verify_table(flatcc_table_verifier_descriptor_t *td);
static int TsetlinMachine_Model_verify_table(flatcc_table_verifier_descriptor_t *td);

static int TsetlinMachine_Parameters_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* threshold */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* n_literals */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* n_clauses */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* n_classes */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* max_state */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 1, 1) /* min_state */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 1, 1) /* boost_tp */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 4, 4) /* learn_s */)) return ret;
    return flatcc_verify_ok;
}

static inline int TsetlinMachine_Parameters_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_Parameters_identifier, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_Parameters_identifier, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_Parameters_type_identifier, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_Parameters_type_identifier, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &TsetlinMachine_Parameters_verify_table);
}

static inline int TsetlinMachine_Parameters_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &TsetlinMachine_Parameters_verify_table);
}

static int TsetlinMachine_ClauseWeightsTensor_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 2, 2, INT64_C(2147483647)) /* weights */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 4, 4, INT64_C(1073741823)) /* shape */)) return ret;
    return flatcc_verify_ok;
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_ClauseWeightsTensor_identifier, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_ClauseWeightsTensor_identifier, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_ClauseWeightsTensor_type_identifier, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_ClauseWeightsTensor_type_identifier, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static inline int TsetlinMachine_ClauseWeightsTensor_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &TsetlinMachine_ClauseWeightsTensor_verify_table);
}

static int TsetlinMachine_AutomatonStatesTensor_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 1, 1, INT64_C(4294967295)) /* states */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 4, 4, INT64_C(1073741823)) /* shape */)) return ret;
    return flatcc_verify_ok;
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_AutomatonStatesTensor_identifier, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_AutomatonStatesTensor_identifier, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_AutomatonStatesTensor_type_identifier, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_AutomatonStatesTensor_type_identifier, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static inline int TsetlinMachine_AutomatonStatesTensor_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &TsetlinMachine_AutomatonStatesTensor_verify_table);
}

static int TsetlinMachine_Model_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 1, &TsetlinMachine_Parameters_verify_table) /* params */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 1, &TsetlinMachine_AutomatonStatesTensor_verify_table) /* automaton_states */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 2, 1, &TsetlinMachine_ClauseWeightsTensor_verify_table) /* clause_weights */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 3, 0) /* literal_names */)) return ret;
    return flatcc_verify_ok;
}

static inline int TsetlinMachine_Model_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_Model_identifier, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_Model_identifier, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, TsetlinMachine_Model_type_identifier, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, TsetlinMachine_Model_type_identifier, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &TsetlinMachine_Model_verify_table);
}

static inline int TsetlinMachine_Model_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &TsetlinMachine_Model_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* TSETLIN_MACHINE_VERIFIER_H */
