#ifndef TSETLIN_MACHINE_READER_H
#define TSETLIN_MACHINE_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct TsetlinMachine_Parameters_table *TsetlinMachine_Parameters_table_t;
typedef struct TsetlinMachine_Parameters_table *TsetlinMachine_Parameters_mutable_table_t;
typedef const flatbuffers_uoffset_t *TsetlinMachine_Parameters_vec_t;
typedef flatbuffers_uoffset_t *TsetlinMachine_Parameters_mutable_vec_t;
typedef const struct TsetlinMachine_ClauseWeightsTensor_table *TsetlinMachine_ClauseWeightsTensor_table_t;
typedef struct TsetlinMachine_ClauseWeightsTensor_table *TsetlinMachine_ClauseWeightsTensor_mutable_table_t;
typedef const flatbuffers_uoffset_t *TsetlinMachine_ClauseWeightsTensor_vec_t;
typedef flatbuffers_uoffset_t *TsetlinMachine_ClauseWeightsTensor_mutable_vec_t;
typedef const struct TsetlinMachine_AutomatonStatesTensor_table *TsetlinMachine_AutomatonStatesTensor_table_t;
typedef struct TsetlinMachine_AutomatonStatesTensor_table *TsetlinMachine_AutomatonStatesTensor_mutable_table_t;
typedef const flatbuffers_uoffset_t *TsetlinMachine_AutomatonStatesTensor_vec_t;
typedef flatbuffers_uoffset_t *TsetlinMachine_AutomatonStatesTensor_mutable_vec_t;
typedef const struct TsetlinMachine_Model_table *TsetlinMachine_Model_table_t;
typedef struct TsetlinMachine_Model_table *TsetlinMachine_Model_mutable_table_t;
typedef const flatbuffers_uoffset_t *TsetlinMachine_Model_vec_t;
typedef flatbuffers_uoffset_t *TsetlinMachine_Model_mutable_vec_t;
#ifndef TsetlinMachine_Parameters_file_identifier
#define TsetlinMachine_Parameters_file_identifier 0
#endif
/* deprecated, use TsetlinMachine_Parameters_file_identifier */
#ifndef TsetlinMachine_Parameters_identifier
#define TsetlinMachine_Parameters_identifier 0
#endif
#define TsetlinMachine_Parameters_type_hash ((flatbuffers_thash_t)0x493484f1)
#define TsetlinMachine_Parameters_type_identifier "\xf1\x84\x34\x49"
#ifndef TsetlinMachine_Parameters_file_extension
#define TsetlinMachine_Parameters_file_extension "bin"
#endif
#ifndef TsetlinMachine_ClauseWeightsTensor_file_identifier
#define TsetlinMachine_ClauseWeightsTensor_file_identifier 0
#endif
/* deprecated, use TsetlinMachine_ClauseWeightsTensor_file_identifier */
#ifndef TsetlinMachine_ClauseWeightsTensor_identifier
#define TsetlinMachine_ClauseWeightsTensor_identifier 0
#endif
#define TsetlinMachine_ClauseWeightsTensor_type_hash ((flatbuffers_thash_t)0x238d3458)
#define TsetlinMachine_ClauseWeightsTensor_type_identifier "\x58\x34\x8d\x23"
#ifndef TsetlinMachine_ClauseWeightsTensor_file_extension
#define TsetlinMachine_ClauseWeightsTensor_file_extension "bin"
#endif
#ifndef TsetlinMachine_AutomatonStatesTensor_file_identifier
#define TsetlinMachine_AutomatonStatesTensor_file_identifier 0
#endif
/* deprecated, use TsetlinMachine_AutomatonStatesTensor_file_identifier */
#ifndef TsetlinMachine_AutomatonStatesTensor_identifier
#define TsetlinMachine_AutomatonStatesTensor_identifier 0
#endif
#define TsetlinMachine_AutomatonStatesTensor_type_hash ((flatbuffers_thash_t)0x134de6fe)
#define TsetlinMachine_AutomatonStatesTensor_type_identifier "\xfe\xe6\x4d\x13"
#ifndef TsetlinMachine_AutomatonStatesTensor_file_extension
#define TsetlinMachine_AutomatonStatesTensor_file_extension "bin"
#endif
#ifndef TsetlinMachine_Model_file_identifier
#define TsetlinMachine_Model_file_identifier 0
#endif
/* deprecated, use TsetlinMachine_Model_file_identifier */
#ifndef TsetlinMachine_Model_identifier
#define TsetlinMachine_Model_identifier 0
#endif
#define TsetlinMachine_Model_type_hash ((flatbuffers_thash_t)0xf9accfc2)
#define TsetlinMachine_Model_type_identifier "\xc2\xcf\xac\xf9"
#ifndef TsetlinMachine_Model_file_extension
#define TsetlinMachine_Model_file_extension "bin"
#endif



struct TsetlinMachine_Parameters_table { uint8_t unused__; };

static inline size_t TsetlinMachine_Parameters_vec_len(TsetlinMachine_Parameters_vec_t vec)
__flatbuffers_vec_len(vec)
static inline TsetlinMachine_Parameters_table_t TsetlinMachine_Parameters_vec_at(TsetlinMachine_Parameters_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(TsetlinMachine_Parameters_table_t, vec, i, 0)
__flatbuffers_table_as_root(TsetlinMachine_Parameters)

__flatbuffers_define_scalar_field(0, TsetlinMachine_Parameters, threshold, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, TsetlinMachine_Parameters, n_literals, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, TsetlinMachine_Parameters, n_clauses, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(3, TsetlinMachine_Parameters, n_classes, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(4, TsetlinMachine_Parameters, max_state, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(5, TsetlinMachine_Parameters, min_state, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(6, TsetlinMachine_Parameters, boost_tp, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(7, TsetlinMachine_Parameters, learn_s, flatbuffers_float, float, 0.00000000f)

struct TsetlinMachine_ClauseWeightsTensor_table { uint8_t unused__; };

static inline size_t TsetlinMachine_ClauseWeightsTensor_vec_len(TsetlinMachine_ClauseWeightsTensor_vec_t vec)
__flatbuffers_vec_len(vec)
static inline TsetlinMachine_ClauseWeightsTensor_table_t TsetlinMachine_ClauseWeightsTensor_vec_at(TsetlinMachine_ClauseWeightsTensor_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(TsetlinMachine_ClauseWeightsTensor_table_t, vec, i, 0)
__flatbuffers_table_as_root(TsetlinMachine_ClauseWeightsTensor)

__flatbuffers_define_vector_field(0, TsetlinMachine_ClauseWeightsTensor, weights, flatbuffers_int16_vec_t, 0)
__flatbuffers_define_vector_field(1, TsetlinMachine_ClauseWeightsTensor, shape, flatbuffers_uint32_vec_t, 0)

struct TsetlinMachine_AutomatonStatesTensor_table { uint8_t unused__; };

static inline size_t TsetlinMachine_AutomatonStatesTensor_vec_len(TsetlinMachine_AutomatonStatesTensor_vec_t vec)
__flatbuffers_vec_len(vec)
static inline TsetlinMachine_AutomatonStatesTensor_table_t TsetlinMachine_AutomatonStatesTensor_vec_at(TsetlinMachine_AutomatonStatesTensor_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(TsetlinMachine_AutomatonStatesTensor_table_t, vec, i, 0)
__flatbuffers_table_as_root(TsetlinMachine_AutomatonStatesTensor)

__flatbuffers_define_vector_field(0, TsetlinMachine_AutomatonStatesTensor, states, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_vector_field(1, TsetlinMachine_AutomatonStatesTensor, shape, flatbuffers_uint32_vec_t, 0)

struct TsetlinMachine_Model_table { uint8_t unused__; };

static inline size_t TsetlinMachine_Model_vec_len(TsetlinMachine_Model_vec_t vec)
__flatbuffers_vec_len(vec)
static inline TsetlinMachine_Model_table_t TsetlinMachine_Model_vec_at(TsetlinMachine_Model_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(TsetlinMachine_Model_table_t, vec, i, 0)
__flatbuffers_table_as_root(TsetlinMachine_Model)

__flatbuffers_define_table_field(0, TsetlinMachine_Model, params, TsetlinMachine_Parameters_table_t, 1)
__flatbuffers_define_table_field(1, TsetlinMachine_Model, automaton_states, TsetlinMachine_AutomatonStatesTensor_table_t, 1)
__flatbuffers_define_table_field(2, TsetlinMachine_Model, clause_weights, TsetlinMachine_ClauseWeightsTensor_table_t, 1)
__flatbuffers_define_vector_field(3, TsetlinMachine_Model, literal_names, flatbuffers_string_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* TSETLIN_MACHINE_READER_H */
